######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 15 20:42:14 2011
######################################################################

TEMPLATE = app
TARGET = bin/syncer
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/gitlauncher.h
SOURCES += src/gitlauncher.cpp src/main.cpp
