######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 20 00:12:14 2011
######################################################################

TEMPLATE = app
TARGET = bin/restore
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/restore.h
FORMS += src/restore.ui
SOURCES += src/main.cpp src/restore.cpp
