######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 9 20:17:30 2012
######################################################################

TEMPLATE = app
TARGET = rshtest
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += remoteshellrunner.h
SOURCES += remoteshellrunner.cpp rshtest.cpp

LIBS += -lssh
