######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 9 20:17:30 2012
######################################################################

TEMPLATE = app
TARGET = runtest
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += runner.h
SOURCES += runner.cpp runtest.cpp
