######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 9 20:17:30 2012
######################################################################

TEMPLATE = app
TARGET = shruntest
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += shellrunner.h
SOURCES += shellrunner.cpp shruntest.cpp
