######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 20 00:12:14 2011
######################################################################

TEMPLATE = app
TARGET = restore
DEPENDPATH += . 
INCLUDEPATH += . 

# Input
HEADERS += restore.h
FORMS += restore.ui
SOURCES += main.cpp restore.cpp
