######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 15 20:42:14 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gitlauncher.h
SOURCES += gitlauncher.cpp main.cpp
