######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 20 00:12:14 2011
######################################################################

TEMPLATE = app
TARGET = ../bin/undelete
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += undelete.h
FORMS += undelete.ui
SOURCES += main.cpp undelete.cpp
