######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 20 00:12:14 2011
######################################################################

TEMPLATE = app
TARGET = bin/undelete
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/undelete.h
FORMS += src/undelete.ui
SOURCES += src/main.cpp src/undelete.cpp
